FROM node:18-bullseye-slim

WORKDIR /app/

# Install dependencies
RUN apt-get update && apt-get install -y python3 make g++ && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Set python3 as the default Python for node-gyp
ENV PYTHON /usr/bin/python3

COPY . .

RUN npm install -g pnpm
RUN pnpm install --frozen-lockfile



CMD ["pnpm","start:indexer"]