/**
 * @packageDocumentation
 * @module api.functional.prizes
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
export * as proposals from "./proposals";