/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import 'sst'
declare module 'sst' {
  export interface Resource {
    AuthGithubId: {
      type: 'sst.sst.Secret'
      value: string
    }
    AuthGithubSecret: {
      type: 'sst.sst.Secret'
      value: string
    }
    AuthGoogleId: {
      type: 'sst.sst.Secret'
      value: string
    }
    AuthGoogleSecret: {
      type: 'sst.sst.Secret'
      value: string
    }
    AuthResendKey: {
      type: 'sst.sst.Secret'
      value: string
    }
    AuthSecret: {
      type: 'sst.sst.Secret'
      value: string
    }
    AuthTrustHost: {
      type: 'sst.sst.Secret'
      value: string
    }
    CacheTable: {
      name: string
      type: 'sst.aws.Dynamo'
    }
    ChainId: {
      type: 'sst.sst.Secret'
      value: string
    }
    DatabaseUrl: {
      type: 'sst.sst.Secret'
      value: string
    }
    EventBus: {
      arn: string
      name: string
      type: 'sst.aws.Bus'
    }
    ImageUploads: {
      name: string
      type: 'sst.aws.Bucket'
    }
    IndexerPrizeFactoryStartBlock: {
      type: 'sst.sst.Secret'
      value: string
    }
    IndexerPrizeStartBlock: {
      type: 'sst.sst.Secret'
      value: string
    }
    IndexerRpcUrl: {
      type: 'sst.sst.Secret'
      value: string
    }
    LoopsApiKey: {
      type: 'sst.sst.Secret'
      value: string
    }
    NextPublicWalletConnectProjectId: {
      type: 'sst.sst.Secret'
      value: string
    }
<<<<<<< HEAD
    OpenAiApiKey: {
      type: 'sst.sst.Secret'
      value: string
=======
    "PaymentSecretKey": 
      "type": "sst.sst.Secret"
      "value": string
    "Router": 
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    "RpcUrl": 
      "type": "sst.sst.Secret"
      "value": string
>>>>>>> 98f97a1dc917c3a1a9eb4c7e1bd53a2e32d26365
    RpcUrl: 
      type: 'sst.sst.Secret'
      value: string
    
    {
      arn: string
      type: 'sst.aws.Function'
    
    {
      type: 'sst.sst.Secret'
      value: string
    
<<<<<<< HEAD
    WalletPaymentInfraApi: 
      type: 'sst.sst.Secret'
      value: string
=======
    "WebhookSecret": 
      "type": "sst.sst.Secret"
      "value": string
    "schedulerRole": 
      "arn": string
      "type": "aws.iam/role.Role"
>>>>>>> 98f97a1dc917c3a1a9eb4c7e1bd53a2e32d26365
    schedulerRole: 
      arn: string
      type: 'aws.iam/role.Role'
    website: {
    
      url: string
    }
  }
}