#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"



npm run build ||
(
    echo '❌👷🔨❌ Better call Bob... Because your build failed ❌👷🔨❌
            Next build failed: View the errors above to see why. 
    '
    false;
)

echo '✅ Awesome good code, I am pushing it your branch now 🚀🚀🚀'