#!/usr/bin/env sh

# Get the list of files to be pushed
files_to_push=$(git diff --cached --name-only)

# Check if any files in the 'backend' directory are staged for push
if echo "$files_to_push" | grep -q "^backend/"; then
    echo "Building backend..."
    (cd backend && pnpm run build) || {
        echo '❌👷🔨❌ Better call Bob... Because your backend build failed ❌👷🔨❌
            Backend build failed: View the errors above to see why.'
        exit 1
    }
fi

# Check if any files in the 'client' directory are staged for push
if echo "$files_to_push" | grep -q "^apps/client/"; then
    echo "Building client..."
    (cd apps/client && pnpm run build) || {
        echo '❌👷🔨❌ Better call Bob... Because your client build failed ❌👷🔨❌
            Client build failed: View the errors above to see why.'
        exit 1
    }
fi

# Check if any files in the 'contracts' directory are staged for commit
if echo "$staged_files" | grep -q "^apps/contracts/"; then
    echo "Changes made to contracts."
fi


echo '✅ Awesome good code, I am pushing it to your branch now 🚀🚀🚀'
