#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

pnpm run check-format ||
(
    echo '🤢🤮🤢🤮 Its FOKING RAW - Your styling looks disgusting. 🤢🤮🤢🤮
            Prettier Check Failed. Run npm run format, add changes and try commit again.';
    false;
)

echo '🤔🤔🤔🤔... Alright.... Code looks good to me... Checking your eslint now 🤔🤔🤔🤔'

# Check ESLint Standards
pnpm run lint ||
(
        echo '😤🏀👋😤 Get that weak shit out of here! 😤🏀👋😤 
                ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false; 
)

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'