#!/usr/bin/env sh

# Get the list of staged files
staged_files=$(git diff --cached --name-only)

# Check if any files in the 'backend' directory are staged for commit
if echo "$staged_files" | grep -q "^backend/"; then
    echo "Running checks for backend..."
    (cd backend && pnpm run format) || {
        echo '🤢🤮🤢🤮 Its FOKING RAW - Your styling looks disgusting. 🤢🤮🤢🤮
            Prettier Check Failed. Run pnpm run format, add changes and try commit again.'
        exit 1
    }
    (cd backend && pnpm run lint) || {
        echo '😤🏀👋😤 Get that weak shit out of here! 😤🏀👋😤 
                ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        exit 1
    }
fi

# Check if any files in the 'client' directory are staged for commit
if echo "$staged_files" | grep -q "^apps/client/"; then
    cd apps/client && pnpm run format && cd ../../
    echo "Running checks for client..."
    (cd apps/client && pnpm run check-format) || {
        echo '🤢🤮🤢🤮 Its FOKING RAW - Your styling looks disgusting. 🤢🤮🤢🤮
            Prettier Check Failed. Run pnpm run format, add changes and try commit again.'
        exit 1
    }
    (cd apps/client && pnpm run lint) || {
        echo '😤🏀👋😤 Get that weak shit out of here! 😤🏀👋😤 
                ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        exit 1
    }
fi

# Check if any files in the 'contracts' directory are staged for commit
if echo "$staged_files" | grep -q "^apps/contracts/"; then
    echo "Changes made to contracts."
fi

git add .

echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'
